// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type Accommodation = { key: string, name: string, link: string, notes: string, emoji: string | null, hero_image: string | null, };
