// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type City = { key: string, name: string, chinese_name: string, tagline: string, description: string, emoji: string | null, hero_image: string | null, lat: number | null, lng: number | null, };
