// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type CreateDay = { date: string, city_key: string, accommodation_key: string | null, };
