// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type CreateCity = { name: string, chinese_name: string | null, tagline: string | null, lat: number | null, lng: number | null, };
