// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type UpdateAccommodation = { name: string | null, link: string | null, notes: string | null, emoji: string | null, hero_image: string | null, };
