// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type UpdateCity = { name: string | null, chinese_name: string | null, tagline: string | null, description: string | null, emoji: string | null, hero_image: string | null, lat: number | null, lng: number | null, };
