// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type UpdateDay = { date: string | null, city_key: string | null, accommodation_key: string | null, notes: string | null, emoji: string | null, hero_image: string | null, };
